openapi: 3.0.3
info:
  title: SECRET SANTA
  description: API for web site handling SECRET SANTA events.
  contact:
    email: touron.camille@icloud.com
  version: 1.0.0
servers:
  - url: "{protocol}://{server}"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      server:
        default: localhost:3000
tags:
  - name: member
    description: Everything about members.
  - name: event
    description: Everything about events.
  - name: participations
    description: Everything about participations.
  - name: request
    description: Everything about request.
  - name: admin
    description: Everything for admin.
paths:
  /help:
    get:
      tags:
        - member
      summary: Get all routes except admin ones.
      description: Help to list all routes except admin ones.
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /login:
    post:
      tags:
        - member
        - admin
      summary: login
      description: login
      requestBody:
          $ref: "#/components/requestBodies/Login"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /signin:
    post:
      tags:
        - member
        - admin
      summary: Create member.
      description: Create member by signin with unique pseudo and complexe password.
      security: []
      requestBody:
          $ref: "#/components/requestBodies/SignIn"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /admin/help:
    get:
      tags:
        - admin
      summary: Get all routes.
      description: Help to list all routes.
      security: 
        - member : []
        - admin : []
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /admin/members:
    get:
      tags:
        - admin
      summary: Get all members.
      description: ""
      security: 
        - member : []
        - admin : []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Members'
  /admin/members/{id}:
    get:
      tags:
        - admin
        - member
      summary: Get all members.
      description: Get member by id.
      security: 
        - member : []
        - admin : []
      parameters:
        - name: id
          in: path
          description: member id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
    delete:
      tags:
        - member
        - admin
      summary: Supprimer un adhérent.
      description: Supprimer un adhérent supprime les avis qu'il a rédiger.
      operationId: delete member
      parameters:
        - name: id
          in: path
          description: Id de l'adhérent.
          required: true
          schema:
            type: integer
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /admin/members/{pseudo}:
    get:
      tags:
        - admin
        - member
      summary: Get all members.
      description: Get member by pseudo.
      operationId: getMemberBypseudo
      security: 
        - member : []
        - admin : []
      parameters:
        - name: pseudo
          in: path
          description: member pseudo
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
    delete:
      tags:
        - member
        - admin
      summary: Supprimer un adhérent.
      description: Supprimer un adhérent supprime les avis qu'il a rédiger.
      parameters:
        - name: pseudo
          in: path
          description: pseudo of member
          required: true
          schema:
            type: integer
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
components:
  securitySchemes:
    member:
      type: http
      scheme: bearer
      bearerFormat: JWT
    admin:
      type: apiKey
      in: header
      name: X-ADMIN-KEY
  parameters:
    idInPath:
      required: true
      name: id
      in: path
      schema:
        type: integer
  schemas:
    Login:
      type: object
      properties:
        pseudo:
            type: string
            example: "TheBoss"
        password:
          type: string
          example: "etvhtrdvtyesvy"
      xml:
        name: Login
    SignIn:
      type: object
      properties:
        pseudo:
            type: string
            example: "TheBoss"
        firstname:
          type: string
          example: "Touron"
        lastname:
          type: string
          example: "Camille"
        isAdmin:
          type: boolean
          example: "false"
        password:
          type: string
          example: "etvhtrdvtyesvy"
        mail:
            type: string
            example: "camille.touron@icloud.com"
      xml:
        name: Signin
    Member:
      type: object
      properties:
        pseudo:
            type: string
            example: "TheBoss"
        firstname:
          type: string
          example: "Touron"
        lastname:
          type: string
          example: "Camille"
        isAdmin:
          type: boolean
          example: "false"
        mail:
            type: string
            example: "camille.touron@icloud.com"
      xml:
        name: Signin
    Members:
      type: array
      xml:
        wrapped: true
      items:
        $ref: "#/components/schemas/Member"
  requestBodies:
    Login:
      required: true
      description: Login request body.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Login'
    SignIn:
      required: true
      description: Registration request body.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SignIn'
  responses:
    ServerError:
      description: "Server seems to be in bad shape..."
      content:
        application/json:
          schema:
            type: object
            required: [ success, message ]
            properties:
              success:
                type: boolean
                default: false
                example: false
              message:
                type: string
                default: "Server seems to be in bad shape..."
                example: "Server seems to be in bad shape..."