openapi: 3.0.3
info:
  title: SECRET SANTA
  description: API for web site handling SECRET SANTA events.
  contact:
    email: touroncamille@icloud.com
  version: 1.0.0
servers:
  - url: "{protocol}://{server}"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      server:
        default: localhost:3003
tags:
  - name: member
    description: Everything about members.
  - name: event
    description: Everything about events.
  - name: participations
    description: Everything about participations.
  - name: request
    description: Everything about request.
  - name: admin
    description: Everything for admin.
paths:
  /help:
    get:
      tags:
        - member
      summary: Get all routes except admin ones.
      description: Help to list all routes except admin ones.
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /login:
    post:
      tags:
        - member
        - admin
      summary: login
      description: login
      requestBody:
          $ref: "#/components/requestBodies/Login"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"  
  /cache:
    delete:
      tags:
        - cache
      summary: delete server cache
      description: delete server cache
      responses:
        "500":
          $ref: "#/components/responses/ServerError"    
  /member:
    get:
      tags:
        - member
      summary: Get all members.
      description: ""
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MembersForShowing'
    post:
      tags:
        - member
      summary: Create member.
      description: Create member with complexe password.
      requestBody:
          $ref: "#/components/requestBodies/MemberCreation"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /member/{id}:
    get:
      tags:
        - member
      summary: Get all members.
      description: Get member by id.
      parameters:
        - name: id
          in: path
          description: member id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberForShowing'
    delete:
      tags:
        - member
      summary: Delete member.
      description: Delete member by id.
      parameters:
        - name: id
          in: path
          description: Id de l'adhérent.
          required: true
          schema:
            type: integer
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
    patch:
      tags:
        - member
      summary: Update member.
      description: Update member.
      parameters:
        - name: id
          in: path
          description: Id de l'adhérent.
          required: true
          schema:
            type: integer
      requestBody:
          $ref: "#/components/requestBodies/MemberCreation"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /event:
    get:
      tags:
        - event
      summary: Get all events.
      description: ""
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsForShowing'
    post:
      tags:
        - event
      summary: Create event.
      description: Create event with unique name.
      requestBody:
          $ref: "#/components/requestBodies/EventCreation"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /event/{id}:
    get:
      tags:
        - event
      summary: Get event.
      description: Get event by id.
      parameters:
        - name: id
          in: path
          description: event id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventForShowing'
    delete:
      tags:
        - event
      summary: Delete event.
      description: Delete event by id.
      parameters:
        - name: id
          in: path
          description: Event id.
          required: true
          schema:
            type: integer
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
    patch:
      tags:
        - event
      summary: Update event.
      description: Update event.
      parameters:
        - name: id
          in: path
          description: Id de l'adhérent.
          required: true
          schema:
            type: integer
      requestBody:
          $ref: "#/components/requestBodies/EventCreation"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /participation:
    get:
      tags:
        - participation
      summary: Get all participations.
      description: ""
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipationsForShowing'
    post:
      tags:
        - participation
      summary: Create participation.
      description: Create participation.
      requestBody:
          $ref: "#/components/requestBodies/ParticipationCreation"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
  /participation/{id}:
    get:
      tags:
        - participation
      summary: Get participation.
      description: Get participation by id.
      parameters:
        - name: id
          in: path
          description: participation id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipationForShowing'
    delete:
      tags:
        - participation
      summary: Delete participation.
      description: Delete participation by id.
      parameters:
        - name: id
          in: path
          description: participation id.
          required: true
          schema:
            type: integer
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
    patch:
      tags:
        - participation
      summary: Update participation.
      description: Update participation.
      parameters:
        - name: id
          in: path
          description: Id de l'adhérent.
          required: true
          schema:
            type: integer
      requestBody:
          $ref: "#/components/requestBodies/ParticipationCreation"
      responses:
        "500":
          $ref: "#/components/responses/ServerError"
components:
  securitySchemes:
    member:
      type: http
      scheme: bearer
      bearerFormat: JWT
    admin:
      type: apiKey
      in: header
      name: X-ADMIN-KEY
  parameters:
    idInPath:
      required: true
      name: id
      in: path
      schema:
        type: integer
  schemas:
    Login:
      type: object
      properties:
        mail:
            type: string
            example: "TheBoss"
        password:
          type: string
          example: "etvhtrdvtyesvy"
      xml:
        name: Login
    Member:
      type: object
      properties:
        firstname:
          type: string
          example: "Touron"
        lastname:
          type: string
          example: "Camille"
        isAdmin:
          type: boolean
          example: "false"
        password:
          type: string
          example: "etvhtrdvtyesvy"
        mail:
            type: string
            example: "touroncamille@icloud.com"
      xml:
        name: Member
    MemberForShowing:
      type: object
      properties:
        firstname:
          type: string
          example: "Touron"
        lastname:
          type: string
          example: "Camille"
        isAdmin:
          type: boolean
          example: "false"
        mail:
          type: string
          example: "touroncamille@icloud.com"
      xml:
        name: MemberForShowing
    MembersForShowing:
      type: array
      xml:
        wrapped: true
      items:
        $ref: "#/components/schemas/MemberForShowing"
    EventForShowing:
      type: object
      properties:
        name:
          type: string
          example: "Super fete ynov."
        date:
          type: string
          example: "22-03-1999"
        location:
          type: string
          example: "Toulouse"
      xml:
        name: EventForShowing
    EventsForShowing:
      type: array
      xml:
        wrapped: true
      items:
        $ref: "#/components/schemas/EventForShowing"
    ParticipationForShowing:
      type: object
      properties:
        memberId:
          type: integer
          example: 1
        memberAttributedId:
          type: integer
          example: 2
        eventId:
          type: integer
          example: 3
        isOrganizer:
          type: boolean
          example: true
      xml:
        name: ParticipationForShowing
    ParticipationsForShowing:
      type: array
      xml:
        wrapped: true
      items:
        $ref: "#/components/schemas/ParticipationForShowing"
  requestBodies:
    Login:
      required: true
      description: Login request body.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Login'
    MemberCreation:
      required: true
      description: Member creation request body.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Member'
    EventCreation:
      required: true
      description: Registration request body.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EventForShowing'
    ParticipationCreation:
      required: true
      description: Participation creation request body.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EventForShowing'
  responses:
    ServerError:
      description: "Server seems to be in bad shape..."
      content:
        application/json:
          schema:
            type: object
            required: [ success, message ]
            properties:
              success:
                type: boolean
                default: false
                example: false
              message:
                type: string
                default: "Server seems to be in bad shape..."
                example: "Server seems to be in bad shape..."